{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grobid",
    "module": "grobid-service",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "grobid-service-0.7.1.jar",
          "url": "grobid-service-0.7.1.jar",
          "size": 3234458,
          "sha512": "e96dfdd08f247abcef17a8b21ee29da3b40665812b235c8fb7ca467b2f5b3042f4b1d8141f76c123ca120bbbd8976d41fbf4eb372810888e65794b93251445ae",
          "sha256": "b1b02a13d682dba3ee6990bd3de2b9d6785dfd4231c3a8a8d826069b0e4cfbf8",
          "sha1": "b4d6d3ad13a51b802c25174b9f0b5bc1c9de35b7",
          "md5": "9aea42f6cb05a851f82ebe78afff1d7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cybozu.labs",
          "module": "langdetect",
          "version": {
            "requires": "1.1-20120112"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.rockymadden.stringmetric",
          "module": "stringmetric-core_2.10",
          "version": {
            "requires": "0.27.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "commons-pool",
          "module": "commons-pool",
          "version": {
            "requires": "1.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "commons-dbutils",
          "module": "commons-dbutils",
          "version": {
            "requires": "1.7"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "black.ninia",
          "module": "jep",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.grobid",
          "module": "grobid-core",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.grobid",
          "module": "grobid-trainer",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.dropwizard",
          "module": "dropwizard-core",
          "version": {
            "requires": "1.3.23"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.dropwizard",
          "module": "dropwizard-assets",
          "version": {
            "requires": "1.3.23"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "com.hubspot.dropwizard",
          "module": "dropwizard-guicier",
          "version": {
            "requires": "1.3.5.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.dropwizard",
          "module": "dropwizard-testing",
          "version": {
            "requires": "1.3.23"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.dropwizard",
          "module": "dropwizard-forms",
          "version": {
            "requires": "1.3.23"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.dropwizard",
          "module": "dropwizard-client",
          "version": {
            "requires": "1.3.23"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.dropwizard",
          "module": "dropwizard-auth",
          "version": {
            "requires": "1.3.23"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "javax.activation",
          "module": "activation",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_dropwizard",
          "version": {
            "requires": "0.11.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "io.prometheus",
          "module": "simpleclient_servlet",
          "version": {
            "requires": "0.11.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-jdk14"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grobid-service-0.7.1.jar",
          "url": "grobid-service-0.7.1.jar",
          "size": 3234458,
          "sha512": "e96dfdd08f247abcef17a8b21ee29da3b40665812b235c8fb7ca467b2f5b3042f4b1d8141f76c123ca120bbbd8976d41fbf4eb372810888e65794b93251445ae",
          "sha256": "b1b02a13d682dba3ee6990bd3de2b9d6785dfd4231c3a8a8d826069b0e4cfbf8",
          "sha1": "b4d6d3ad13a51b802c25174b9f0b5bc1c9de35b7",
          "md5": "9aea42f6cb05a851f82ebe78afff1d7d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grobid-service-0.7.1-onejar.jar",
          "url": "grobid-service-0.7.1-onejar.jar",
          "size": 97529304,
          "sha512": "fbfd58c6bc53e5ab608d063f2ab44b0ac0b5c41d057f7c9a0eb77dda4e7fc3ee20c0ae6262215297a7c57a5da254861799b87a9299cafa199afe7f6991c69635",
          "sha256": "1f6b2c8ef8e6b365975f315fda133527915d4ba7d3cc77208dd97417b874aa1f",
          "sha1": "f9e8d43f9df3e4b949aaf06838905685a996bedf",
          "md5": "fa5b142267f1f637c449104becd6717b"
        }
      ]
    }
  ]
}
