{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grobid",
    "module": "grobid-core",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "net.arnx",
          "module": "jsonic",
          "version": {
            "requires": "1.3.10"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "9.6.0-9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "xom",
          "module": "xom",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grobid-core-0.7.1.jar",
          "url": "grobid-core-0.7.1.jar",
          "size": 15688157,
          "sha512": "2f3f1feb31cec8bd0282bb73f7a77a300e90ff2e77aa8c8e6f77fc59b810d7e6448575cdc7485c3bf053b217f93c31942160b29cd22f08dd1df3de408923bcf4",
          "sha256": "6a25dfa91302b7845e2e6b0c82ddc65487255a86c86f9c05c6550dd43b1c5f7d",
          "sha1": "ed990568dc847acfb7ba7096c0362223e93d6a8d",
          "md5": "0f940f0434ac5fcf5fc59f03d0eb56e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cybozu.labs",
          "module": "langdetect",
          "version": {
            "requires": "1.1-20120112"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.rockymadden.stringmetric",
          "module": "stringmetric-core_2.10",
          "version": {
            "requires": "0.27.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "commons-pool",
          "module": "commons-pool",
          "version": {
            "requires": "1.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "commons-dbutils",
          "module": "commons-dbutils",
          "version": {
            "requires": "1.7"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "black.ninia",
          "module": "jep",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "strictly": "1.4.01",
            "requires": "1.4.01"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.18"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.9.9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-common",
          "version": {
            "requires": "4.5.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.opennlp",
          "module": "opennlp-tools",
          "version": {
            "requires": "1.9.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jruby",
          "module": "jruby-complete",
          "version": {
            "requires": "9.2.13.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-log4j12",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "net.arnx",
          "module": "jsonic",
          "version": {
            "requires": "1.3.10"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "net.sf.saxon",
          "module": "Saxon-HE",
          "version": {
            "requires": "9.6.0-9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "xom",
          "module": "xom",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-jdk14",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grobid-core-0.7.1.jar",
          "url": "grobid-core-0.7.1.jar",
          "size": 15688157,
          "sha512": "2f3f1feb31cec8bd0282bb73f7a77a300e90ff2e77aa8c8e6f77fc59b810d7e6448575cdc7485c3bf053b217f93c31942160b29cd22f08dd1df3de408923bcf4",
          "sha256": "6a25dfa91302b7845e2e6b0c82ddc65487255a86c86f9c05c6550dd43b1c5f7d",
          "sha1": "ed990568dc847acfb7ba7096c0362223e93d6a8d",
          "md5": "0f940f0434ac5fcf5fc59f03d0eb56e0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grobid-core-0.7.1-onejar.jar",
          "url": "grobid-core-0.7.1-onejar.jar",
          "size": 78857569,
          "sha512": "855a4bbea716410de3e8a4fc75f340b78a92806a16167a3bae64697b6bb1da1509b040be4917f1cbea2beb0f0b668a426cabd89adf8890c144068352a4109001",
          "sha256": "ea61ebbe7141210c95fa28da205cb0739c92fc3c821c5f57d547dbceedb9eaad",
          "sha1": "757c84d2164cc5d6e8ce4246f0ff6d9a3b7758f4",
          "md5": "6deb82edd89fb0fa780ac558e7139f5f"
        }
      ]
    }
  ]
}
